import { NextResponse } from 'next/server';
import { execSync } from 'child_process';
import path from 'path';
import fs from 'fs';

/**
 * POST /api/providers/claude-cli/setup-token/save
 *
 * Saves a Claude CLI setup token to the target (host or container).
 *
 * Body:
 *   token: string           — the OAuth token generated by `claude setup-token`
 *   agent?: string          — container name (optional)
 *   profileId?: string      — optional profile identifier (default: claude-cli:setup)
 *   setEnv?: boolean        — also inject CLAUDE_CODE_OAUTH_TOKEN in the env/profile
 */
export async function POST(req: Request) {
  try {
    const { token, agent, profileId, setEnv } = await req.json();
    if (!token || token.length < 20) {
      return NextResponse.json({ error: 'Valid token required (min 20 chars)' }, { status: 400 });
    }

    const safeAgent = agent ? agent.replace(/[^a-zA-Z0-9_-]/g, '') : null;
    const isLocal = !safeAgent;
    const pid = profileId || 'claude-cli:setup';

    // ── 1. Save to auth-profiles.json ─────────────────────────────────────
    if (isLocal) {
      const home = process.env.HOME || '/root';
      const agentDir = `${home}/.openclaw/agents/main/agent`;

      // Save as auth profile
      try {
        const profilePath = `${agentDir}/auth-profiles.json`;
        let raw = '{}';
        try { raw = fs.readFileSync(profilePath, 'utf-8'); } catch {}
        const profiles = JSON.parse(raw);
        if (!profiles.profiles) profiles.profiles = {};
        profiles.profiles[pid] = {
          provider: 'claude-cli',
          kind: 'token',
          token,
          profileId: pid,
          updatedAt: Date.now(),
        };
        fs.writeFileSync(profilePath, JSON.stringify(profiles, null, 2));
      } catch {}

      // Add to models.json as a configured provider
      try {
        const modelsPath = `${agentDir}/models.json`;
        let raw = '{}';
        try { raw = fs.readFileSync(modelsPath, 'utf-8'); } catch {}
        const models = JSON.parse(raw);
        if (!models.auth) models.auth = {};
        if (!Array.isArray(models.auth.providers)) models.auth.providers = [];
        const existingIdx = models.auth.providers.findIndex((p: any) =>
          p.provider === 'claude-cli' || p.provider === 'anthropic'
        );
        const entry = { provider: 'claude-cli', kind: 'token', profileId: pid };
        if (existingIdx >= 0) {
          models.auth.providers[existingIdx] = { ...models.auth.providers[existingIdx], ...entry };
        } else {
          models.auth.providers.push(entry);
        }
        fs.writeFileSync(modelsPath, JSON.stringify(models, null, 2));
      } catch {}

      // Also save to vault.json for persistence across agent rebuilds
      try {
        const vaultPath = path.join(process.cwd(), 'vault.json');
        let vault: any = { providers: [], services: [], permissions: [] };
        try { vault = JSON.parse(fs.readFileSync(vaultPath, 'utf-8')); } catch {}
        if (!vault.services) vault.services = [];
        const existingSvcIdx = vault.services.findIndex((s: any) => s.service === 'claude-cli');
        const svcEntry = { service: 'claude-cli', token, updatedAt: Date.now() };
        if (existingSvcIdx >= 0) {
          vault.services[existingSvcIdx] = svcEntry;
        } else {
          vault.services.push(svcEntry);
        }
        // Also add as provider
        if (!vault.providers) vault.providers = [];
        const existingProvIdx = vault.providers.findIndex((p: any) => p.provider === 'claude-cli');
        const provEntry = { provider: 'claude-cli', apiKey: token, updatedAt: Date.now() };
        if (existingProvIdx >= 0) {
          vault.providers[existingProvIdx] = provEntry;
        } else {
          vault.providers.push(provEntry);
        }
        fs.writeFileSync(vaultPath, JSON.stringify(vault, null, 2), { mode: 0o600 });
      } catch {}

      // Optionally set the env var via a config file
      if (setEnv) {
        try {
          // Write to a .env file the agent can source
          const envFile = `${home}/.openclaw/agents/main/agent/.env`;
          const envContent = `CLAUDE_CODE_OAUTH_TOKEN=${token}\n`;
          fs.appendFileSync(envFile, envContent);
        } catch {}
      }

      // Restart gateway to pick up changes
      try {
        execSync('kill $(ps aux | grep "[n]ode.*openclaw" | awk "{print $2}") 2>/dev/null || true', { timeout: 5000 });
      } catch {}
    } else {
      // ── Agent container ─────────────────────────────────────────────────
      const container = safeAgent!;
      const dataDir = '/data/.openclaw/agents/main/agent';

      // Save auth profile
      try {
        const raw = execSync(
          `docker exec ${container} sh -c "cat ${dataDir}/auth-profiles.json 2>/dev/null || echo '{}'"`,
          { timeout: 5000, encoding: 'utf-8', maxBuffer: 128 * 1024 }
        );
        const profiles = JSON.parse(raw);
        if (!profiles.profiles) profiles.profiles = {};
        profiles.profiles[pid] = {
          provider: 'claude-cli',
          kind: 'token',
          token,
          profileId: pid,
          updatedAt: Date.now(),
        };
        const b64 = Buffer.from(JSON.stringify(profiles, null, 2)).toString('base64');
        execSync(`docker exec ${container} sh -c "echo '${b64}' | base64 -d > ${dataDir}/auth-profiles.json"`, { timeout: 5000 });
      } catch {}

      // Update models.json
      try {
        const raw = execSync(
          `docker exec ${container} sh -c "cat ${dataDir}/models.json 2>/dev/null || echo '{}'"`,
          { timeout: 5000, encoding: 'utf-8', maxBuffer: 128 * 1024 }
        );
        const models = JSON.parse(raw);
        if (!models.auth) models.auth = {};
        if (!Array.isArray(models.auth.providers)) models.auth.providers = [];
        const existingIdx = models.auth.providers.findIndex((p: any) =>
          p.provider === 'claude-cli' || p.provider === 'anthropic'
        );
        const entry = { provider: 'claude-cli', kind: 'token', profileId: pid };
        if (existingIdx >= 0) {
          models.auth.providers[existingIdx] = { ...models.auth.providers[existingIdx], ...entry };
        } else {
          models.auth.providers.push(entry);
        }
        const b64 = Buffer.from(JSON.stringify(models, null, 2)).toString('base64');
        execSync(`docker exec ${container} sh -c "echo '${b64}' | base64 -d > ${dataDir}/models.json"`, { timeout: 5000 });
      } catch {}

      // Optionally set env
      if (setEnv) {
        try {
          execSync(
            `docker exec ${container} sh -c 'echo "CLAUDE_CODE_OAUTH_TOKEN=${token}" >> ${dataDir}/.env'`,
            { timeout: 5000 },
          );
        } catch {}
      }

      // Restart gateway in container
      try {
        execSync(
          `docker exec ${container} sh -c 'kill -TERM $(ps aux | grep "[n]ode.*openclaw" | awk "{print \\$2}") 2>/dev/null || kill -TERM $(ps aux | grep "[n]ode.*server\\.mjs" | awk "{print \\$2}") 2>/dev/null; sleep 2'`,
          { timeout: 15000 },
        );
      } catch {}
    }

    return NextResponse.json({
      status: 'ok',
      profileId: pid,
      method: isLocal ? 'local-files' : 'container-files',
      message: 'Claude CLI token saved. Gateway restarted to pick up changes.',
    });
  } catch (e: any) {
    return NextResponse.json({ error: e.message }, { status: 500 });
  }
}
